In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('data/Titanic-Dataset.csv')

In [5]:
df = df.drop('Cabin',axis=1)

In [6]:
df['Embarked']= df['Embarked'].fillna(df['Embarked'].mode()[0])

In [7]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [8]:
df['Sex'] = df['Sex'].map({'male':0 , 'female':1})
df = pd.get_dummies(df,columns=['Embarked'],drop_first=True)
df = df.drop(['Name','Ticket','PassengerId'],axis=1)

In [ ]:
df.info()
df.head()

In [9]:
X = df.drop(['Survived'],axis=1)
y = df['Survived']

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [40]:
from sklearn.linear_model import LogisticRegression

In [41]:
model = LogisticRegression()

In [42]:
model.fit(X_train_scaled,y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default sol

In [43]:
prediction = model.predict(X_test_scaled)

In [44]:
compare = pd.DataFrame({
    'Acutal':y_test,
    'Prediction':prediction
})

In [17]:
from sklearn.metrics import accuracy_score , precision_score , recall_score , f1_score , confusion_matrix

In [48]:
print('Accuracy:',accuracy_score(y_test,prediction))
print('Precision:',precision_score(y_test,prediction))
print('Recall:',recall_score(y_test,prediction))
print('F1_score:',f1_score(y_test,prediction))
print('Confusion Matrix:\n',confusion_matrix(y_test,prediction))

Accuracy: 0.8100558659217877
Precision: 0.7857142857142857
Recall: 0.7432432432432432
F1_score: 0.7638888888888888
Confusion Matrix:
 [[90 15]
 [19 55]]


In [49]:
from sklearn.ensemble import RandomForestClassifier

In [50]:
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train_scaled,y_train)

,"random_state random_state: int, RandomState instance or None, default=NoneControls both the randomness of the bootstrapping of the samples usedwhen building trees (if ``bootstrap=True``) and the sampling of thefeatures to consider when looking for the best split at each node(if ``max_features < n_features``).See :term:`Glossary <random_state>` for details.",42
,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstr

In [51]:
rf_predictions = rf_model.predict(X_test_scaled)

In [52]:
print("Accuracy:", accuracy_score(y_test, rf_predictions))
print("Precision:", precision_score(y_test, rf_predictions))
print("Recall:", recall_score(y_test, rf_predictions))
print("F1 Score:", f1_score(y_test, rf_predictions))
print("Confusion Matrix:\n", confusion_matrix(y_test, rf_predictions))

Accuracy: 0.7988826815642458
Precision: 0.7638888888888888
Recall: 0.7432432432432432
F1 Score: 0.7534246575342466
Confusion Matrix:
 [[88 17]
 [19 55]]


In [53]:
from sklearn.tree import DecisionTreeClassifier

In [56]:
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train_scaled,y_train)
dt_predictions = dt_model.predict(X_test_scaled)

In [57]:
print("Accuracy:", accuracy_score(y_test, dt_predictions))
print("Precision:", precision_score(y_test, dt_predictions))
print("Recall:", recall_score(y_test, dt_predictions))
print("F1 Score:", f1_score(y_test, dt_predictions))

Accuracy: 0.7877094972067039
Precision: 0.7432432432432432
Recall: 0.7432432432432432
F1 Score: 0.7432432432432432


In [60]:
dt_model_limit = DecisionTreeClassifier(max_depth=4,random_state=42)
dt_model_limit.fit(X_train_scaled,y_train)
dt_predictions_limited = dt_model_limit.predict(X_test_scaled)

In [62]:
print("Accuracy:", accuracy_score(y_test, dt_predictions_limited))
print("Precision:", precision_score(y_test, dt_predictions_limited))
print("Recall:", recall_score(y_test, dt_predictions_limited))
print("F1 Score:", f1_score(y_test, dt_predictions_limited))

Accuracy: 0.7988826815642458
Precision: 0.8392857142857143
Recall: 0.6351351351351351
F1 Score: 0.7230769230769231


In [63]:
print("No limit - Train accuracy:", dt_model.score(X_train_scaled, y_train))
print("No limit - Test accuracy:", dt_model.score(X_test_scaled, y_test))

print("Limited - Train accuracy:", dt_model_limit.score(X_train_scaled, y_train))
print("Limited - Test accuracy:", dt_model_limit.score(X_test_scaled, y_test))

No limit - Train accuracy: 0.9789325842696629
No limit - Test accuracy: 0.7877094972067039
Limited - Train accuracy: 0.8398876404494382
Limited - Test accuracy: 0.7988826815642458


In [64]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier()
knn_model.fit(X_train_scaled,y_train)
knn_predictions = knn_model.predict(X_test_scaled)

In [66]:
print("Accuracy:", accuracy_score(y_test, knn_predictions))
print("Precision:", precision_score(y_test, knn_predictions))
print("Recall:", recall_score(y_test, knn_predictions))
print("F1 Score:", f1_score(y_test, knn_predictions))
print("Confusion Matrix:\n", confusion_matrix(y_test, knn_predictions))

Accuracy: 0.8044692737430168
Precision: 0.782608695652174
Recall: 0.7297297297297297
F1 Score: 0.7552447552447552
Confusion Matrix:
 [[90 15]
 [20 54]]


In [67]:
from sklearn.neighbors import KNeighborsClassifier
knn_model_limit = KNeighborsClassifier(n_neighbors=4)
knn_model_limit.fit(X_train_scaled,y_train)
knn_predictions_limit = knn_model_limit.predict(X_test_scaled)

In [68]:
print("Accuracy:", accuracy_score(y_test, knn_predictions_limit))
print("Precision:", precision_score(y_test, knn_predictions_limit))
print("Recall:", recall_score(y_test, knn_predictions_limit))
print("F1 Score:", f1_score(y_test, knn_predictions_limit))
print("Confusion Matrix:\n", confusion_matrix(y_test, knn_predictions_limit))

Accuracy: 0.7932960893854749
Precision: 0.8245614035087719
Recall: 0.6351351351351351
F1 Score: 0.7175572519083969
Confusion Matrix:
 [[95 10]
 [27 47]]


In [69]:
print("No limit - Train accuracy:", knn_model.score(X_train_scaled, y_train))
print("No limit - Test accuracy:", knn_model.score(X_test_scaled, y_test))

print("Limited - Train accuracy:", knn_model_limit.score(X_train_scaled, y_train))
print("Limited - Test accuracy:", knn_model_limit.score(X_test_scaled, y_test))

No limit - Train accuracy: 0.8679775280898876
No limit - Test accuracy: 0.8044692737430168
Limited - Train accuracy: 0.8539325842696629
Limited - Test accuracy: 0.7932960893854749


In [14]:
from sklearn.svm import SVC
svm_model = SVC(random_state=42)
svm_model.fit(X_train_scaled,y_train)
svm_predictions = svm_model.predict(X_test_scaled)

In [73]:
print("Accuracy:", accuracy_score(y_test, svm_predictions))
print("Precision:", precision_score(y_test, svm_predictions))
print("Recall:", recall_score(y_test, svm_predictions))
print("F1 Score:", f1_score(y_test, svm_predictions))
print("Confusion Matrix:\n", confusion_matrix(y_test, svm_predictions))

Accuracy: 0.8212290502793296
Precision: 0.8387096774193549
Recall: 0.7027027027027027
F1 Score: 0.7647058823529411
Confusion Matrix:
 [[95 10]
 [22 52]]


In [15]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto']
}

grid_search = GridSearchCV(SVC(random_state=42), param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train_scaled, y_train)

print("Best parameters:", grid_search.best_params_)
print("Best cross-validation accuracy:", grid_search.best_score_)

Best parameters: {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}
Best cross-validation accuracy: 0.8314291342460358


In [19]:
best_svm = grid_search.best_estimator_
test_predictions = best_svm.predict(X_test_scaled)

print("Test Accuracy:", accuracy_score(y_test, test_predictions))
print("Test Precision:", precision_score(y_test, test_predictions))
print("Test Recall:", recall_score(y_test, test_predictions))
print("Test F1:", f1_score(y_test, test_predictions))

Test Accuracy: 0.8212290502793296
Test Precision: 0.8387096774193549
Test Recall: 0.7027027027027027
Test F1: 0.7647058823529411


In [76]:
from sklearn.naive_bayes import GaussianNB
nb_model = GaussianNB()
nb_model.fit(X_train_scaled,y_train)
nb_predictions = nb_model.predict(X_test_scaled)

In [77]:
print("Accuracy:", accuracy_score(y_test, nb_predictions))
print("Precision:", precision_score(y_test, nb_predictions))
print("Recall:", recall_score(y_test, nb_predictions))
print("F1 Score:", f1_score(y_test, nb_predictions))
print("Confusion Matrix:\n", confusion_matrix(y_test, nb_predictions))

Accuracy: 0.770949720670391
Precision: 0.72
Recall: 0.7297297297297297
F1 Score: 0.7248322147651006
Confusion Matrix:
 [[84 21]
 [20 54]]


In [20]:
import joblib
joblib.dump(best_svm, 'titanic_best_svm_model.pkl')
joblib.dump(scaler, 'titanic_scaler.pkl')

['titanic_scaler.pkl']